[velox]
build_args = [
    '-trimpath',
    '-ldflags',
    '-s -X github.com/roadrunner-server/roadrunner/v2024/internal/meta.version=${VERSION} -X github.com/roadrunner-server/roadrunner/v2024/internal/meta.buildTime=${TIME}'
]

[roadrunner]
ref = "v2024.1.2"

[github]
[github.token]
token = "${RT_TOKEN}"

# ref -> master, commit or tag
[github.plugins]
# LOGS
appLogger = { ref = "v4.4.0", owner = "roadrunner-server", repository = "app-logger" }
logger = { ref = "v4.4.0", owner = "roadrunner-server", repository = "logger" }
lock = { ref = "v4.7.0", owner = "roadrunner-server", repository = "lock" }
rpc = { ref = "v4.4.0", owner = "roadrunner-server", repository = "rpc" }

# CENTRIFUGE BROADCASTING PLATFORM
centrifuge = { ref = "v4.9.0", owner = "roadrunner-server", repository = "centrifuge" }

# WORKFLOWS ENGINE
temporal = { ref = "v4.7.0", owner = "temporalio", repository = "roadrunner-temporal" }

# METRICS
metrics = { ref = "v4.3.0", owner = "roadrunner-server", repository = "metrics" }

# HTTP + MIDDLEWARE
http = { ref = "v4.7.0", owner = "roadrunner-server", repository = "http" }
gzip = { ref = "v4.3.0", owner = "roadrunner-server", repository = "gzip" }
prometheus = { ref = "v4.3.0", owner = "roadrunner-server", repository = "prometheus" }
headers = { ref = "v4.4.0", owner = "roadrunner-server", repository = "headers" }
static = { ref = "v4.3.0", owner = "roadrunner-server", repository = "static" }
proxy = { ref = "v4.3.0", owner = "roadrunner-server", repository = "proxy_ip_parser" }
#cache = { ref = "v1.6.49", owner = "darkweak", repository = "souin", folder = "/plugins/roadrunner" }

# OpenTelemetry
otel = { ref = "v4.5.0", owner = "roadrunner-server", repository = "otel" }

# SERVER
server = { ref = "v4.8.0", owner = "roadrunner-server", repository = "server" }

# SERVICE aka lightweit systemd
service = { ref = "v4.7.0", owner = "roadrunner-server", repository = "service" }

# JOBS
jobs = { ref = "v4.9.0", owner = "roadrunner-server", repository = "jobs" }

# FILESERVER (static files)
fileserver = { ref = "v4.3.0", owner = "roadrunner-server", repository = "fileserver" }

# gRPC plugin
grpc = { ref = "v4.8.0", owner = "roadrunner-server", repository = "grpc" }

# HEALTHCHECKS + READINESS CHECKS
status = { ref = "v4.6.0", owner = "roadrunner-server", repository = "status" }

# TCP for the RAW TCP PAYLOADS
tcp = { ref = "v4.5.0", owner = "roadrunner-server", repository = "tcp" }

fileWatch = { ref = "master", owner = "LaserLiga", repository = "rr_file_watch" }

[log]
level = "debug"
mode = "development"